/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.lenebf.plugin.al

import com.android.build.gradle.AppExtension
import com.lenebf.plugin.al.transform.LoggerTransform
import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
public class ActivityLoggerPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a transform
        def android = project.extensions.getByType(AppExtension)
        android.registerTransform(new LoggerTransform())
    }
}
